# Generated by Django 2.1.3 on 2018-11-18 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20181110_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 18, 19, 17, 38, 308276), verbose_name='%H:%M'),
            preserve_default=False,
        ),
    ]
