# Generated by Django 2.1.3 on 2018-11-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_reminder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
    ]
